framework:
    cache:
        app: cache.adapter.filesystem
        pools:
            email.templates:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600

            email.stats:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
