framework:
    messenger:
        failure_transport: failed

        transports:
            # Transports pour différentes priorités d'emails
            high_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 5000
                retry_strategy:
                    max_retries: 5
                    multiplier: 1.5

            normal_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 30000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            low_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 2
                    multiplier: 3

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 10000
                retry_strategy:
                    max_retries: 10
                    multiplier: 1.2

            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Messages d'email personnalisés
            App\Message\SendEmailMessage:
                - high_priority

            # Messages Symfony par défaut
            Symfony\Component\Mailer\Messenger\SendEmailMessage: normal_priority
            Symfony\Component\Notifier\Message\ChatMessage: normal_priority
            Symfony\Component\Notifier\Message\SmsMessage: high_priority
