monolog:
    channels:
        - deprecation
        - security
        - business
        - performance

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            error:
                type: stream
                path: "%kernel.logs_dir%/errors.log"
                level: error
                channels: ["!event", "!deprecation"]

            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: info
                channels: [security]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

            email:
                type: rotating_file
                path: '%kernel.logs_dir%/email.log'
                level: info
                max_files: 10
                channels: ['!event']

            email_errors:
                type: rotating_file
                path: '%kernel.logs_dir%/email_errors.log'
                level: error
                max_files: 30
                channels: ['!event', '!deprecation']

            email_critical:
                type: rotating_file
                path: '%kernel.logs_dir%/email_critical.log'
                level: critical
                max_files: 30
                channels: ['!event', '!deprecation']

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
                buffer_size: 50

            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

            test_errors:
                type: stream
                path: "%kernel.logs_dir%/test_errors.log"
                level: error
                channels: ["!event", "!deprecation"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50

            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 30
                formatter: monolog.formatter.json

            error:
                type: rotating_file
                path: "%kernel.logs_dir%/errors.log"
                level: error
                max_files: 90
                channels: ["!event", "!deprecation"]
                formatter: monolog.formatter.json

            security:
                type: rotating_file
                path: "%kernel.logs_dir%/security.log"
                level: info
                channels: [security]
                max_files: 365
                formatter: monolog.formatter.json

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: rotating_file
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecation.log"
                max_files: 30
                formatter: monolog.formatter.json
