security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Webhook endpoints
        webhook:
            pattern: ^/webhook
            security: false

        # API publique
        api_public:
            pattern: ^/api/(health|ping)
            security: false

        # Pages publiques
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: dashboard_index
                failure_path: app_login
                failure_handler: App\Security\LoginFailureHandler
                success_handler: App\Security\LoginSuccessHandler

            logout:
                path: app_logout
                target: home
                invalidate_session: true
                delete_cookies:
                    REMEMBERME: { path: /, domain: ~ }

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 jours (30 * 24 * 60 * 60)
                path: /
                domain: ~
                secure: auto
                httponly: true
                samesite: lax
                always_remember_me: false
                remember_me_parameter: _remember_me

            switch_user:
                provider: app_user_provider
                parameter: _switch_user
                role: ROLE_PREVIOUS_ADMIN

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/verify-email, roles: PUBLIC_ACCESS }
        - { path: ^/resend-verification, roles: PUBLIC_ACCESS }
        - { path: ^/api/validate-email, roles: PUBLIC_ACCESS }
        - { path: ^/pricing, roles: PUBLIC_ACCESS }
        - { path: ^/features, roles: PUBLIC_ACCESS }
        - { path: ^/about, roles: PUBLIC_ACCESS }
        - { path: ^/contact, roles: PUBLIC_ACCESS }
        - { path: ^/demo, roles: PUBLIC_ACCESS }
        - { path: ^/terms, roles: PUBLIC_ACCESS }
        - { path: ^/privacy, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS }

        # Webhooks publics
        - { path: ^/webhook, roles: PUBLIC_ACCESS }

        # API publics
        - { path: ^/api/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/ping, roles: PUBLIC_ACCESS }

        # Dashboard and protected pages
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/projects, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }

        # Administration
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

when@dev:
    security:
        firewalls:
            main:
                remember_me:
                    lifetime: 7776000 # 90 jours en dev (plus pratique pour développeurs)

when@prod:
    security:
        firewalls:
            main:
                stateless: false
                remember_me:
                    secure: true # Forcer HTTPS
                    httponly: true
                    samesite: strict
