parameters:
    # Application configuration
    app.mailer_from_email: '%env(MAILER_FROM_EMAIL)%'
    app.base_url: '%env(APP_URL)%'
    app.ai.provider: '%env(AI_PROVIDER)%'
    app.ai.openai_key: '%env(OPENAI_API_KEY)%'
    app.ai.groq_key: '%env(GROQ_API_KEY)%'
    app.stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    app.stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    #### SERVICES D'IA ####
    App\Service\AiSuggestionService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $aiProvider: '%app.ai.provider%'
            $openaiApiKey: '%app.ai.openai_key%'
            $groqApiKey: '%app.ai.groq_key%'
    ## SERVICES D'IA ####

    #### SERVICES DE NOTIFICATIONS ####
    App\EventListener\LoginEventListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
    #### SERVICES DE NOTIFICATIONS ####

    #### SERVICES D'EMAIL ####
    App\Service\Email\EmailService:
        arguments:
            $senderEmail: '%env(MAILER_FROM_EMAIL)%'
            $senderName: '%env(MAILER_FROM_NAME)%'
            $maxRetries: '%env(MAILER_MAX_RETRIES)%'
            $retryDelayMs: '%env(MAILER_RETRY_DELAY_MS)%'

    App\Service\Email\EmailQueueService:
        arguments:
            $messageBus: '@messenger.bus.default'

    App\MessageHandler\SendEmailMessageHandler:
        tags:
            - { name: messenger.message_handler }

    App\Service\Email\EmailMonitoringService:
        arguments:
            $enableMetrics: '%env(bool:ENABLE_EMAIL_METRICS)%'
    ## SERVICES D'EMAIL ####
